daemon off;
worker_processes   1;
error_log         logs/error.log error;
working_directory  /home/work/github/ngx_realtime_module/build/nginx/dumps;
# Edit the above line to point to a directory.
worker_rlimit_core 2000M;

events {
  worker_connections 8;
}


http {
    realtime_enabled   on;
    realtime_monitor_from_content_phase on;
    realtime_log_level alert;
    realtime_syslog_info       syslog:server=127.0.0.1:5145 error;
    realtime_syslog_queue_interval 3s;
    realtime_syslog_send_batch_size 2;

    server {
        listen 7779;
        root html;

        location / {
            try_files "Faker" /dl/;
        }

        location /dl/ {
            default_type application/octet-stream;
            add_header   Content-Disposition 'attachment; filename="final.zip"';

            internal;

            realtime_monitor on;
            realtime_error_log off;
            realtime_syslog on;
            realtime_interval 2s;
            realtime_format     'uid!#!${arg_uid}|ri!#!${realtime_interval}|bbs!#!${realtime_body_bytes_sent}|rte!#!${realtime_time_elapsed}|rrc!#!${realtime_request_completion}|fresh!#!${realtime_is_fresh}|rc!#!${request_completion}|queue_size!#!${realtime_queue_size}';
            try_files /final.zip @e404;
        }

        location @e404 {
            return 200 "no file";
        }
    }
}
